name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v1
        id: versions

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{steps.versions.outputs.elixir}}
          otp-version: ${{steps.versions.outputs.erlang}}
      
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.*', 'config/*.exs') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Install frontend deps
        run: mix install

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Format
        run: mix format --check-formatted

      - name: Credo
        run: mix credo

      - name: Run tests
        run: mix test
